### ISSUE TITLE
Create a project on Vercel and set up a deployment from master branch

### ISSUE THREAD

**Issue by sapozhnikovay** [iegorov/e-reception#3]
Use this guide to import existing repository to a Vercel project:
https://vercel.com/docs/getting-started-with-vercel/import

Here are the details for Next.js deployment on Vercel:
https://vercel.com/docs/frameworks/nextjs

**Comment by iegorov** [comment]
Project url: https://vercel.com/ivan-egorovs-projects/e-reception/4KNhEffDKf6vnLG6wAF8fWeifo6y
